/* ==========================================================================
   Barq — Content Security Policy generator
   The site ships two kinds of inline <script>: the pre-paint theme/language
   setter (identical on every page) and the JSON-LD blocks (per page). Rather
   than weaken the policy with 'unsafe-inline', each one is hashed and listed.
   Re-run after any change to the layout or a page's structured data:
     node tools/build.mjs && node tools/gen-csp.mjs
   ========================================================================== */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const root = new URL('../', import.meta.url);
const files = (await readdir(root)).filter((f) => f.endsWith('.html'));

const hashes = new Set();
for (const file of files) {
  const src = await readFile(new URL(file, root), 'utf8');
  for (const m of src.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
    hashes.add(`'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`);
  }
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(' ')}`,
  "style-src 'self'",                 /* no inline style attributes anywhere — see tools/audit-csp */
  "img-src 'self' data:",             /* data: covers the select-chevron background */
  "font-src 'self'",                  /* Cairo is self-hosted */
  "connect-src 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "frame-src 'none'",
  "object-src 'none'",
  "base-uri 'none'",
  "manifest-src 'self'",
  'upgrade-insecure-requests',
].join('; ');

const SECURITY = {
  'Content-Security-Policy': csp,
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'X-Frame-Options': 'DENY',
};

/* Vercel */
await writeFile(new URL('vercel.json', root), JSON.stringify({
  $schema: 'https://openapi.vercel.sh/vercel.json',
  cleanUrls: true,
  trailingSlash: false,
  headers: [
    { source: '/(.*)', headers: Object.entries(SECURITY).map(([key, value]) => ({ key, value })) },
    {
      source: '/assets/(.*)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
    {
      source: '/(.*).html',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=0, must-revalidate' }],
    },
  ],
}, null, 2) + '\n');

/* Netlify / Cloudflare Pages */
const netlify = [
  '# Generated by tools/gen-csp.mjs — do not edit by hand.',
  '/*',
  ...Object.entries(SECURITY).map(([k, v]) => `  ${k}: ${v}`),
  '',
  '/assets/*',
  '  Cache-Control: public, max-age=31536000, immutable',
  '',
  '/*.html',
  '  Cache-Control: public, max-age=0, must-revalidate',
  '',
].join('\n');
await writeFile(new URL('_headers', root), netlify);

console.log(`Hashed ${hashes.size} inline script(s) across ${files.length} pages.`);
console.log('Wrote vercel.json and _headers.');
